-- ============================================================
-- CantinApp - Seed Sentori da aromi-data.js v1.06
-- ============================================================
-- Esegui DOPO v0.13_admin_sentori.sql
-- Popola famiglie_olfattive, sottocategorie_olfattive, sentori
-- con i ~440 sentori già esistenti (tutti con stato='attivo').
-- ============================================================

BEGIN;

-- 1. FAMIGLIE
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('fruttato', 'Fruttato', '#C0392B', 0) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('floreale', 'Floreale', '#E8A0BF', 1) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('vegetale', 'Vegetale', '#27AE60', 2) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('minerale', 'Minerale', '#7F8C8D', 3) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('erbe_aromatiche', 'Erbe aromatiche', '#7AAB45', 4) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('speziato', 'Speziato', '#A06B30', 5) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('tostato', 'Tostato', '#6B4226', 6) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('balsamico', 'Balsamico', '#16A085', 7) ON CONFLICT (key) DO NOTHING;
INSERT INTO famiglie_olfattive (key, label, color, ordine) VALUES ('etereo', 'Etereo', '#9B59B6', 8) ON CONFLICT (key) DO NOTHING;

-- 2. SOTTOCATEGORIE
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'agrumi', 'Agrumi', ARRAY['bianco','spumante','rosato','passito']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'polpa_bianca', 'Frutta a polpa bianca', ARRAY['bianco','spumante','rosato']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'polpa_gialla', 'Frutta a polpa gialla', ARRAY['bianco','spumante','rosato','passito']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutti_tropicali', 'Frutti tropicali', ARRAY['bianco','spumante','passito']::TEXT[], 3) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutti_rossi', 'Frutti rossi', ARRAY['rosso','rosato','spumante']::TEXT[], 4) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutti_scuri', 'Frutti scuri / Bacche nere', ARRAY['rosso','rosato','spumante']::TEXT[], 5) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'drupacee_rosse', 'Drupacee scure', ARRAY['rosso','rosato','passito']::TEXT[], 6) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutta_matura', 'Frutta matura', ARRAY['rosso','bianco','rosato','passito','liquoroso']::TEXT[], 7) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutta_sotto_spirito', 'Frutta sotto spirito', ARRAY['rosso','passito','liquoroso']::TEXT[], 8) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'confetture', 'Confetture', ARRAY['rosso','passito','liquoroso','bianco']::TEXT[], 9) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutta_secca', 'Frutta secca', ARRAY['rosso','bianco','passito','liquoroso']::TEXT[], 10) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutta_liofilizzata', 'Frutta liofilizzata', ARRAY['passito','liquoroso']::TEXT[], 11) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('fruttato', 'frutti_guscio', 'Frutti col guscio', ARRAY['bianco','rosso','passito','liquoroso']::TEXT[], 12) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'fiori_bianchi', 'Fiori bianchi', ARRAY['bianco','spumante','rosato','passito']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'fiori_gialli', 'Fiori gialli', ARRAY['bianco','spumante','rosato','passito']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'fiori_rossi', 'Fiori rossi e rosa', ARRAY['rosso','rosato','spumante']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'fiori_appassiti', 'Fiori appassiti', ARRAY['rosso','passito','liquoroso']::TEXT[], 3) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'fiori_campo', 'Fiori di campo', ARRAY['bianco','rosato','spumante','rosso']::TEXT[], 4) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('floreale', 'miele', 'Miele', ARRAY['bianco','passito','liquoroso']::TEXT[], 5) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'vegetale_positivo', 'Vegetali positivi', ARRAY['rosso','bianco','rosato','spumante']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'vegetale_negativo', 'Vegetali da scarsa maturità', ARRAY['rosso','bianco','rosato','spumante']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'ortaggi', 'Ortaggi', ARRAY['bianco','rosato','spumante','rosso']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'sottobosco_evoluto', 'Sottobosco evoluto', ARRAY['rosso','passito','liquoroso']::TEXT[], 3) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'bosso', 'Bosso e solforati varietali', ARRAY['bianco','spumante']::TEXT[], 4) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('vegetale', 'sentori_animali', 'Sentori vinosi/animali (specifici)', ARRAY['rosso']::TEXT[], 5) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('minerale', 'pietre_terreni', 'Pietre e terreni', ARRAY['rosso','bianco','rosato','spumante','passito']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('minerale', 'ossidanti', 'Note ossidanti', ARRAY['rosso','bianco','rosato','spumante','passito']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('minerale', 'marini', 'Note marine', ARRAY['bianco','spumante','rosato']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('erbe_aromatiche', 'erbe_fresche', 'Erbe fresche (terpenico-aromatiche)', ARRAY['rosso','bianco','rosato','spumante']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('erbe_aromatiche', 'erbe_officinali', 'Erbe officinali ed essiccate', ARRAY['rosso','bianco','passito','liquoroso']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('speziato', 'spezie_dolci', 'Spezie dolci (barrique)', ARRAY['rosso','bianco','passito','spumante','liquoroso']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('speziato', 'spezie_legno_grande', 'Spezie da legno grande', ARRAY['rosso','bianco','passito','liquoroso']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('speziato', 'spezie_piccanti', 'Spezie piccanti', ARRAY['rosso','rosato','liquoroso','bianco']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('speziato', 'spezie_orientali', 'Spezie orientali/colorate', ARRAY['rosso','bianco','passito','liquoroso']::TEXT[], 3) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'tostature_barrique', 'Tostature da barrique', ARRAY['rosso','bianco','passito','liquoroso','spumante']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'affumicato', 'Affumicati', ARRAY['rosso','liquoroso','bianco']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'empireumatici', 'Sentori empireumatici (legno tostato)', ARRAY['rosso','passito','liquoroso']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'tabacco_cuoio', 'Tabacco e cuoio', ARRAY['rosso','passito','liquoroso']::TEXT[], 3) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'frutta_secca_tostata', 'Frutta secca tostata', ARRAY['rosso','bianco','passito','liquoroso','spumante']::TEXT[], 4) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('tostato', 'pane_lieviti', 'Pane e lieviti (metodo classico)', ARRAY['spumante','bianco']::TEXT[], 5) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('balsamico', 'balsamici_giovani', 'Balsamici (vini giovani)', ARRAY['rosso','bianco','rosato','spumante']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('balsamico', 'balsamici_evoluti', 'Balsamici (evolutivi)', ARRAY['rosso','passito','liquoroso']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('etereo', 'etereo_evolutivo', 'Etereo evolutivo (positivi)', ARRAY['rosso','bianco','passito','liquoroso','spumante']::TEXT[], 0) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('etereo', 'etereo_negativo', 'Etereo da alcol poco integrato (negativi)', ARRAY['rosso','bianco','rosato','spumante','passito','liquoroso']::TEXT[], 1) ON CONFLICT (famiglia_key, key) DO NOTHING;
INSERT INTO sottocategorie_olfattive (famiglia_key, key, label, compat, ordine) VALUES ('etereo', 'animali_selvaggina', 'Animali / Selvaggina', ARRAY['rosso','passito']::TEXT[], 2) ON CONFLICT (famiglia_key, key) DO NOTHING;

-- 3. SENTORI
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'agrumi canditi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'arancia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'bergamotto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cedro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'lime', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'limone', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mandarino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pompelmo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pompelmo rosa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'scorza d''arancia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'agrumi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cotogna', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cotognata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fico bianco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'kiwi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mela', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mela golden', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mela verde', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pera', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pera williams', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pesca bianca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'uva spina', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_bianca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'albicocca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'melone', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'melone bianco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'nespola', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pesca gialla', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'susina gialla', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'polpa_gialla' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ananas', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'banana', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutto della passione', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'guaiava', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'litchi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mango', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'maracuja', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'papaia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_tropicali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'amarena', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ciliegia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fragola', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fragolina di bosco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'lampone', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'melograno', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ribes rosso', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cassis', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gelso nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mirtillo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mirtillo nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mora', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mora di rovo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ribes nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sambuco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_scuri' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'marasca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'drupacee_rosse' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'prugna', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'drupacee_rosse' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'prugna nera', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'drupacee_rosse' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'visciola', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'drupacee_rosse' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta a maturazione spinta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_matura' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta matura', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_matura' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta surmatura', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_matura' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'amarena sotto spirito', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_sotto_spirito' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ciliegia sotto spirito', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_sotto_spirito' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta sotto spirito', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_sotto_spirito' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'prugna sotto spirito', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_sotto_spirito' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'confettura di ciliegie', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'confettura di lamponi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'confettura di mirtilli', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'confettura di prugne', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'marmellata di agrumi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'marmellata di pesche', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'confetture' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'albicocca secca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'dattero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fico secco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta candita', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'prugna secca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'uva passa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_secca' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fragola liofilizzata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_liofilizzata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'frutta liofilizzata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_liofilizzata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'lampone liofilizzato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutta_liofilizzata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mandorla', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_guscio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'nocciola', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_guscio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'noce', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_guscio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pinolo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_guscio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pistacchio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'fruttato' AND key = 'frutti_guscio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'biancospino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori di mandorlo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori di pesco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gardenia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gelsomino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'giglio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'iris bianco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'magnolia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mughetto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sambuco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_bianchi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'acacia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'camomilla', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'caprifoglio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori d''arancio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ginestra', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mimosa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tiglio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_gialli' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'glicine', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ibisco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'lavanda', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'peonia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'rosa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'rosa rossa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'violetta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_rossi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori appassiti', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_appassiti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'potpourri', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_appassiti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'rosa appassita', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_appassiti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'violetta appassita', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_appassiti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori di campo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_campo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fiori freschi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'fiori_campo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cera d''api', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'miele' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'miele', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'miele' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'miele di acacia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'miele' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'miele di castagno', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'miele' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'miele millefiori', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'floreale' AND key = 'miele' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'felce', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fieno', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'foglia di tè', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'muschio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'paglia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sottobosco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tè nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tè verde', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_positivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'erba tagliata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'foglia di pomodoro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'foglia di ribes nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'foglia di violetta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'melanzana', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'peperone verde', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pomodoro fresco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'vegetale_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'asparago', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'carciofo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cetriolo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'finocchio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'passata di pomodoro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'piselli', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'ortaggi' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fungo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fungo porcino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'humus', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tartufo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tartufo bianco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tartufo nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'terra umida', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sottobosco_evoluto' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'bosso', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'bosso' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pipì di gatto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'bosso' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'foxy', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sentori_animali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'vinoso', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'vegetale' AND key = 'sentori_animali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ardesia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gesso', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'grafite', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pietra bagnata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pietra di fiume', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pietra focaia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'silice', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tufo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'pietre_terreni' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cherosene', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fumo di candela', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fumé', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'idrocarburi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'nafta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'polvere da sparo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'ossidanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'alga', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'marini' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'conchiglia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'marini' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'iodio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'marini' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'salato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'marini' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'salmastro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'minerale' AND key = 'marini' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'basilico', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'erba luigia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'maggiorana', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'menta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'menta piperita', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'origano fresco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'rosmarino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'salvia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'timo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'verbena', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_fresche' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'alloro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'erbe alpine', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'erbe officinali', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'macchia mediterranea', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'origano secco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tè', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'erbe_aromatiche' AND key = 'erbe_officinali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'anice', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'anice stellato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cannella', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cardamomo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'chiodi di garofano', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'noce moscata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'vaniglia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_dolci' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'liquirizia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_legno_grande' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'macis', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_legno_grande' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'noce moscata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_legno_grande' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ginepro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'paprika', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pepe bianco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pepe nero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pepe rosa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pepe verde', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'peperoncino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'zenzero', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_piccanti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'curcuma', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_orientali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'curry', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_orientali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pimento', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_orientali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'zafferano', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'speziato' AND key = 'spezie_orientali' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cacao', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'caffè', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'caffè tostato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'caramello', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cioccolato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cioccolato fondente', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'crème brûlée', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'vaniglia tostata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tostature_barrique' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'affumicato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'affumicato' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'arrosto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'affumicato' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fumo', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'affumicato' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fumo di candela', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'affumicato' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'fumo di legna', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'affumicato' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'asfalto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'bitume', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'catrame', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'creosoto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'goudron', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pece', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'empireumatici' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cuoio', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cuoio conciato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pellame', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tabacco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tabacco da pipa', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'tabacco dolce', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'tabacco_cuoio' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'arachide tostata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'frutta_secca_tostata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mandorla tostata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'frutta_secca_tostata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'nocciola tostata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'frutta_secca_tostata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'noce tostata', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'frutta_secca_tostata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pinolo tostato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'frutta_secca_tostata' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'biscotto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'burro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'crosta di pane', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'lievito', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pan brioche', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pane tostato', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pasticceria', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'tostato' AND key = 'pane_lieviti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'eucalipto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_giovani' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'eucalipto fresco', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_giovani' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'menta', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_giovani' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'menta piperita', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_giovani' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'abete', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'conifera', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ginepro', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'incenso', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'mirra', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'pino', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'resina', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'balsamico' AND key = 'balsamici_evoluti' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cera', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'cera d''api', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'ceralacca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gommalacca', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'legno antico', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'legno antiquario', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sapone', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sapone di Marsiglia', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_evolutivo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'acetone', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'colla', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'smalto', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'solvente', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'vernice', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'etereo_negativo' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'gibier', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'rustico', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'salumi', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sangue', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'selvaggina', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;
INSERT INTO sentori (sottocategoria_id, nome, stato) SELECT id, 'sugo di carne', 'attivo' FROM sottocategorie_olfattive WHERE famiglia_key = 'etereo' AND key = 'animali_selvaggina' ON CONFLICT DO NOTHING;

COMMIT;

-- Riepilogo: 9 famiglie, 45 sottocategorie, 272 sentori

-- Verifica post-import:
-- SELECT COUNT(*) AS famiglie FROM famiglie_olfattive;
-- SELECT COUNT(*) AS sottocategorie FROM sottocategorie_olfattive;
-- SELECT COUNT(*) AS sentori_attivi FROM sentori WHERE stato='attivo';